version: "3"
services:
  db:
    image: postgres:alpine3.15
    restart: always
    container_name: vianda_va_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=blog

volumes:
  pgdata:
    driver: local
